FROM ubuntu:latest

RUN yum -y install git gcc gcc-c++ make automake wget meson ca-c* libgcrypt* glib2* utf8proc* openssl-devel ncurses* libbgcrypt* glib2-devel utf8proc* openssl-devel ncurses*

RUN git clone
http://github.com/irssi/irssi.git
WORKDIR irssi
RUN meson setup build