FROM ubuntu:latest

RUN apt-get -y update

RUN apt-get -y install git

RUN apt -y install cargo

RUN apt-get update && apt-get install -y tzdata

RUN apt -y install cmake

RUN apt install -y libssl-dev

RUN apt install -y pkg-config

RUN git clone https://github.com/deltachat/deltachat-core-rust.git

WORKDIR deltachat-core-rust

RUN cmake -B build . -DCMAKE_INSTALL_PREFIX=/usr

RUN cmake --build build
