version: '1'

services:
  builder:
    image: k4zu/mk284011labs:rc01
    build:
      dockerfile: Dockerfile-build
      context: .
  tester:
    depends_on:
      - builder
    build:
      dockerfile: Dockerfile-test
      context: .