pipeline {
  agent any
     stages {
        stage('Build') { 
        steps {
         sh'''
         ls
         cd GCL/04/MK284011/
         ls
         docker build -t nodejs/example .
         cd Test
         docker build -t nodejs/example2 .
         '''
        }
     }
  stage('Test') { 
     steps {
         sh '''
         docker run easy/sauce2:latest
         '''
     }
  }   
  }
}