apiVersion: apps/v1
kind: Deployment
metadata:
  name: papas-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: papas
          image: stephengrider/multi-client
          ports:
            - containerPort: 2137