FROM ubuntu:latest as build-vol

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y
RUN apt install -y nodejs npm git

RUN git clone https://github.com/lyhd/reactjs

WORKDIR /reactjs

RUN npm install

CMD ["npm","run","build"]
