version: '3'
services:
      react-build: 
              build:
                context: .
                dockerfile: Dockerfile-build
      react-tests: 
              depends_on: 
              - react-build
              build:
                context: .
                dockerfile: Dockerfile-tests 