pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                rm -rf MDO2022
                git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022.git
                cd MDO2022/
                git checkout TW301196
                cd GCL/01/TW301196_Lab2 
                docker build -t build:latest -f ./dockerfile-build .
                '''
            }
             post {
                 success {
                     mail to: 'twalasik97@gmail.com', subject: "Pipeline built succeded", body: "Twój program został poprawnie zbudowany"
                 }
             }
        }
        stage('Test') {
            steps {
                    
                    sh '''
                    cd MDO2022/GCL/01/TW301196_Lab2
                    docker build -t test:latest -f ./dockerfile-test .
                    '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                
                  cd MDO2022/GCL/01/TW301196_Lab2
                  docker build -t deploy:latest -f ./dockerfile-deploy .
                
                '''
            }
        }
    }
}
