FROM ubuntu:latest

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update
RUN apt-get install curl -y
RUN curl -fsSl https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get install git nodejs -y

RUN git clone https://github.com/jterkalski/react-app.git
WORKDIR /react-app
RUN npm install 

RUN npm run build

CMD ["npm", "start"]