FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install git -y 

RUN git clone https://github.com/deltachat/deltachat-desktop.git


WORKDIR deltachat-desktop
   
RUN apt install nodejs -y
# Geaographic area: 8
# Time zone: 60
   
RUN apt install curl -y
RUN apt install sudo -y
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN sudo apt install nodejs -y
RUN apt update

RUN npm install
RUN npm audit fix
RUN npm run build
