pipeline {

     agent any
     
     environment {
		DOCKERHUB_CREDENTIALS=credentials('agtal')
	}
    
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t app . -f GCL/03/AT285937/lab2/dockerfile-bldr'               
            }
            post {
            success {
            	mail to: 'atalik000@gmail.com', subject: "Budowanie ukonczone pomyslnie", body: "Budowanie ukonczone pomyslnie: ${BUILD_URL}"
            }
            failure {
            	mail to: 'atalik000@gmail.com', subject: "Blad budowania", body: "Bledy w budowaniu: ${BUILD_URL}"
            }
          }            
        }
        stage('Test') {
            steps {
                sh 'docker build -t test . -f MDO2022/GCL/03/AT285937/lab2/dockerfile-tst'     
            }
         post {
            success {
            	mail to: 'atalik000@gmail.com', subject: "Test uruchomiony pomyslnie", body: "Test uruchomiony pomyslnie: ${BUILD_URL}"
            }
            failure {
            	mail to: 'atalik000@gmail.com', subject: "Blad testowania", body: "Bledy w testowaniu: ${BUILD_URL}"
            }
         }
    }
          stage('Login')
            {
                steps {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                }
            }
          stage('Deploy') {
                steps {
                    sh '''
                    docker tag app:latest agtal/mdo2022_deploy:1.2
                    docker push agtal/mdo2022_deploy:1.2
                    '''
                }
            post {
                success {
            	    mail to: 'atalik000@gmail.com', subject: "Deploy dziala:", body: "Deploy dziala: ${BUILD_URL}"
                }
                failure {
            	mail to: 'atalik000@gmail.com', subject: "Deploy - Blad", body: "Deploy nie dziala: ${BUILD_URL}"
                }
            }
                
        }
  }
}
