pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'docker-compose -f GCL/03/DZ307697/docker-compose.yml build --no-cache build'
            }
        }
        
    }
    
}
