pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    try {
                        sh '''
                        rm -rf MDO2022
                        git config --global user.name "kkachniarz220"
                        git config --global user.email "kkachniarz@protonmail.com"
                        git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022.git
                        cd MDO2022
                        git switch -c KK307668
                        git branch --set-upstream-to=origin/KK307668 KK307668
                        git pull
                        cd GCL/01/KK307668/lab4/assets
                        ls
                        docker build -t bldr:latest . -f ./Dockerfile
                        emailext(body: 'Build step success', mimeType: 'text/html', subject: 'Jenkins', to: 'kkachniarz@protonmail.com')
                        '''
                    } catch(err) {
                        emailext(body: 'Build step err', mimeType: 'text/html', subject: 'Jenkins', to: 'kkachniarz@protonmail.com')
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    try {
                        sh '''
                        cd MDO2022/GCL/01/KK307668/lab4/assets
                        docker build -t test:latest . -f ./Dockerfile-with-tests
                        emailext(body: 'Test step success', mimeType: 'text/html', subject: 'Jenkins', to: 'kkachniarz@protonmail.com')
                        '''
                    } catch(err) {
                        emailext(body: 'Test step err', mimeType: 'text/html', subject: 'Jenkins', to: 'kkachniarz@protonmail.com')
                    }
                }
            }
        }
    }
}
