FROM ubuntu:latest as build-vol

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y
RUN apt install -y nodejs npm git

RUN git clone https://github.com/lyhd/reactjs

WORKDIR /reactjs

RUN npm install

RUN echo "REACT_APP_PUBLIC_URL=http://localhost" > .env

ENV CI=true

RUN npm run build
