pipeline {
    agent any
    
    stages {
        stage('Build'){
            steps {
                sh '''
                rm -rf MDO2022/
                git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022.git
                cd MDO2022/
                git checkout BC301162
                cd GCL/01/BC301162/Lab2/img
                docker build -t docker-ubuntu-react-app:latest -f Dockerfile .
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh '''
                cd MDO2022/GCL/01/BC301162/Lab2/img
                docker build -t tester:latest -f Dockerfile-test .
                '''
            }
        }
    }
}

