FROM ubuntu:latest as build-vol

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl git

RUN curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
RUN sh ./setup_14.sh
RUN apt-get update -y
RUN apt-get install -y nodejs
RUN npm init react-app my-app --use-npm

WORKDIR /my-app

RUN echo "REACT_APP_PUBLIC_URL=http://localhost" > .env

ENV CI=true

RUN npm run build
