FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
RUN sh ./setup_14.sh
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y nodejs npm git
RUN npm init react-app my-app --use-npm

WORKDIR /my-app

CMD ["npm","run","build"]
