pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                rm -rf MDO2022/
                git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022/
                cd MDO2022/
                git checkout PS293243
                cd GCL/02/PS293243
                docker build -t aria2:latest . -f ./aria2-dockerfile --target=base
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                cd MDO2022/GCL/02/PS293243
                docker build -t aria2:latest . -f ./aria2-dockerfile --target=test
                '''
            }
        }
    }
}
