pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                rm -rf MDO2022/
                git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022/
                cd MDO2022/
                git checkout SB307659
                cd GCL/01/SB307659/LAB2
                docker build -t my-react-app:lastest . -f ./Dockerfile
                '''
            }
            post {
                always{
                    mail to: 'szymus358@interia.pl', subject: "Stage Test zakończony pozytywnie", body: "Test zakończony pozytywnie ${BUILD_URL} "
                    }
}
        }
        stage('Test') {
            steps {
                sh '''
                cd MDO2022/GCL/01/SB307659/LAB2
                docker build -t test . -f ./Dockerfile-test
                '''
            }
        post {
                always{
                    mail to: 'szymus358@interia.pl', subject: "Stage Test zakończony pozytywnie", body: "Test zakończony pozytywnie ${BUILD_URL}"
                    }
}    
        }
        }
    }

                    


