pipeline {
    agent{
    dockerfile true
    }
    stages {
        stage('Build') { 
            steps {
                sh'''
                cd GCL/03/JZ307699/Lab_4
                apt-get install npm -y
                docker build -t easy/sauce:latest .
                cd Dockerfile2
                docker build -t easy/sauce2:latest .
                '''
            }
        }
        stage('Test') { 
            steps {
                sh '''
                docker run easy/sauce2:latest
                '''
            }
        }
    }
}
