pipeline {
     environment { 
        registry = "build" 
        registry1 = "test"
        registryCredential = 'docker-hub-credentials' 
        dockerImage = '' 
        dockerImage1 = '' 
    }
    agent any
    stages {
        stage('Build') { 
            steps {
                sh'''
                cd GCL/03/JZ307699/Lab_4
                '''
                dockerImage = docker build -t easy/sauce:latest .
                
                sh'''
                cd Dockerfile2
                docker build -t easy/sauce2:latest .
                '''
                script { 
                    sh 'GCL/03/JZ307699/Lab_4/Dockerfile'
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    sh 'Dockerfile2'
                    dockerImage1 = docker.build registry1 + ":$BUILD_NUMBER" 
                }
            }
            post {
                success {
                    echo 'I succeeded!'
                    //archiveArtifacts artifacts: 'Build/libs/**/*.jar'
                    mail to: 'juligabi@tlen.pl',
                      subject: "Successful Pipeline",
                      body: "Wszystko gra w Build. :)"
                }
                failure {
                    echo 'I failed :('
                    mail to: 'juligabi@tlen.pl',
                        subject: "Failed Pipeline",
                        body: "Coś poszło nie tak w Build. :("
                }
            }
        }
        stage('Test') { 
            steps {
                sh '''
                docker run easy/sauce2:latest
                '''
            }
            post {
            success {
                echo 'I succeeded!'
                mail to: 'juligabi@tlen.pl',
                    subject: "Successful Pipeline: ${currentBuild.fullDisplayName}",
                    body: "Wszystko gra w Test. :)"
            }

            failure {
                echo 'I failed :('
                mail to: 'juligabi@tlen.pl',
                    subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                    body: "Coś poszło nie tak w Test. :("
            }
          }
        }
        stage('Deploy'){
            steps {
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                    dockerImage.push() 
                    dockerImage1.push()
                }
            }
         }
        }
    }
}
