pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh'''
                ls -a
                docker build -t easy/sauce:latest .
                cd Dockerfile2
                sudo docker build -t easy/sauce2:latest .
                '''
            }
        }
        stage('Test') { 
            steps {
                sh '''
                sudo docker run easy/sauce2:latest
                '''
            }
        }
    }
}
