FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl git
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install nodejs

RUN git clone https://github.com/jaspenlind/node-ts-starter-template.git

WORKDIR ./node-ts-starter-template

RUN npm install
RUN npm build