pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh '''
                    docker build -f GCL/03/AT285937/lab2/dockerfile-bldr -t app
                '''
            }
        }
        
    }
    
}
