pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh '''
                    docker build https://github.com/InzynieriaOprogramowaniaAGH/MDO2022/tree/AT285937/GCL/03/AT285937/lab2/dockerfile-bldr .
                '''
            }
        }
        
    }
    
}
