apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-deployment
  labels:
    app: echoserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: hello-minikube
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8081