pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                cd GCL/03/DZ307697
                sh 'docker-compose up build'
            }
        }
        stage('Test') {
            steps {
                cd GCL/03/DZ307697
                sh 'docker-compose up test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
